import delay from './delay';

const articlesFromAlchemy = 
  {
    "status": "OK",
    "usage": "By accessing AlchemyAPI or using information generated by AlchemyAPI, you are agreeing to be bound by the AlchemyAPI Terms of Use: http://www.alchemyapi.com/company/terms.html",
    "totalTransactions": "45",
    "result": {
      "docs": [
        {
          "id": "NjM1NzQ1Nzc4OHwxNDcxMDU3MzQ3",
          "source": {
            "enriched": {
              "url": {
                "text": "Trump says he will be the \u2018law and order\u2019 president. Do we ever need some law and order. ...",
                "title": "Third Party & Independents: Mister Dillon, Mister Dillon !!!"
              }
            },
            "original": {
              "url": "http://www.watchblog.com/thirdparty/archives/009465.html"
            }
          },
          "timestamp": 1471057347
        },
        {
          "id": "NjMxNTc3NTI0N3wxNDcxMDUxNjk3",
          "source": {
            "enriched": {
              "url": {
                "text": " \t\t\t\t\t \t\t\t\t\t\t An opium theft leaves Swearengen trying to find common language with his supplier, as well as navigating tricky waters to deal with the mess. Meanwhile, Silas Adams, bagman for the magistrate from Yankton, arrives with bad\u00A0news for Swearengen; Bullock regrets having raised his hand at the government meeting; Merrick proposes Deadwood's first \"club\"; and an unwelcome Rev. ...",
                "title": "Deadwood: Mister Wu"
              }
            },
            "original": {
              "url": "http://www.tv.com/shows/deadwood/mister-wu-322720/"
            }
          },
          "timestamp": 1471051697
        },
        {
          "id": "NjEzMzc1NzYxMXwxNDcxMDM0MDQ0",
          "source": {
            "enriched": {
              "url": {
                "text": "Maryland star Ben's Cat breezed a half-mile Aug. 12 at Laurel Park in his final timed work before seeking to win the $75,000 Mister Diz Stakes for the seventh successive year Aug. 20.\u00A0\nBred, owned, and trained by Hall of Fame horseman King Leatherbury, the 10-year-old Maryland-bred gelding by Parker's Storm Cat went four furlongs in :49 1/5 over Laurel's main track, registering the fourth-fastest of 12 workouts at the distance. It was the second work for Ben's Cat since his third-place finish in the Parx Dash (gr. ...",
                "title": "Ben's Cat Gears Up for 7th Mister Diz"
              }
            },
            "original": {
              "url": "http://www.bloodhorse.com/horse-racing/articles/214164/bens-cat-gears-up-for-7th-mister-diz"
            }
          },
          "timestamp": 1471034044
        },
        {
          "id": "NjA1NDY5NDgwNXwxNDcxMDI4MTky",
          "source": {
            "enriched": {
              "url": {
                "text": "TUCSON, Ariz., Aug. 12, 2016 /PRNewswire/ -- Mister Car Wash has expanded its Texas footprint with the acquisition of The Car Wash Barn based in Killeen, Texas, according to Casey Lindsay, Director of Acquisitions. \"The Car Wash Barn team developed a great operation and their dedication to the communities they serve is unmatched. ...",
                "title": "Mister Car Wash Adds Six Texas Locations"
              }
            },
            "original": {
              "url": "http://www.prnewswire.com/news-releases/mister-car-wash-adds-six-texas-locations-300313018.html"
            }
          },
          "timestamp": 1471028192
        },
        {
          "id": "NTgyNjAxOTUwOHwxNDcxMDExMDM4",
          "source": {
            "enriched": {
              "url": {
                "text": "In 1987, my primary five class were ushered into the assembly hall at Nazareth House PS by our teacher Patsy Casey to see the important man dressed in black who had come to visit our school. I have no memory of what he talked to us about, I was only nine. ...",
                "title": "Skirting the issue - Mister Bishop do you know my granda?"
              }
            },
            "original": {
              "url": "http://www.derryjournal.com/news/columnists/skirting-the-issue-mister-bishop-do-you-know-my-granda-1-7524448"
            }
          },
          "timestamp": 1471011038
        },
        {
          "id": "NTk2ODQzODI0N3wxNDcxMDAzMDIw",
          "source": {
            "enriched": {
              "url": {
                "text": "Can you hear it? Can you feel it? ...",
                "title": "Hey, mister! Mardi Gras 2017 is 200 days away"
              }
            },
            "original": {
              "url": "http://www.nola.com/mardigras/index.ssf/2016/08/mardi_gras_2017_new_orleans.html"
            }
          },
          "timestamp": 1471003020
        },
        {
          "id": "NTg4MTEwNDYzN3wxNDcwOTk5NjAw",
          "source": {
            "enriched": {
              "url": {
                "text": "\"When we first get the trucks\u00A0they look like blank UPS delivery trucks,\" said Jim Conway, co-owner and vice president of Mister Softee. \"We cut the windows into them, paint them, and deck them out with the equipment to turn them into what you see on the streets.\" ...",
                "title": "The legend of Jersey's own Mister Softee is anything but vanilla"
              }
            },
            "original": {
              "url": "http://www.nj.com/entertainment/index.ssf/2016/08/16_things_you_may_not_know_about_mister_softee.html"
            }
          },
          "timestamp": 1470999600
        }
      ],
      "status": "OK"
    }
  }


const articlesFromBing = 
  {
    "_type": "News",
    "readLink": "https://api.cognitive.microsoft.com/api/v5/news/search?q=microsoft",
    "totalEstimatedMatches": 1330000,
    "value": [
      {
        "name": "When Microsoft needs a tech 'miracle,' this is the team that answers the call",
        "url": "http://www.bing.com/cr?IG=3D19289E347C46BA95F698E3F30282C9&CID=240A0E9368C4603C080907E169F56148&rd=1&h=8AcDSp0ODGXG0ZPn20igpHBAmK7Vrg6jXtIGAJNRL3c&v=1&r=http%3a%2f%2fwww.businessinsider.com%2fmicrosoft-research-peter-lee-interview-2016-8&p=DevEx,5025.1",
        "image": {
          "thumbnail": {
            "contentUrl": "https://www.bing.com/th?id=ON.C4C5E7648D28AFDE2A3C39B7BC80FB8F&pid=News",
            "width": 700,
            "height": 493
          }
        },
        "description": "In 1991, Microsoft founded Microsoft Research, a division for the company's army of PhDs and scientists to pursue the coolest, wildest, most science-fictional ideas they possibly could, with the very non-corporate goal of expanding human knowledge.",
        "about": [
          {
            "readLink": "https://api.cognitive.microsoft.com/api/v5/entities/68d42dd2-f905-5eb2-bd55-8395f7817ba8",
            "name": "Peter Lee"
          },
          {
            "readLink": "https://api.cognitive.microsoft.com/api/v5/entities/f85986a4-3126-0423-6d1d-7a1f6d71e607",
            "name": "Microsoft Research"
          }
        ],
        "provider": [
          {
            "_type": "Organization",
            "name": "The Business Insider"
          }
        ],
        "datePublished": "2016-08-15T20:58:00",
        "category": "ScienceAndTechnology"
      },
      {
        "name": "Microsoft made the perfect Surface Pro 4 cover for NFL fans",
        "url": "http://www.bing.com/cr?IG=3D19289E347C46BA95F698E3F30282C9&CID=240A0E9368C4603C080907E169F56148&rd=1&h=YwuvSnBizwqx9cls6lNeEHfe1PxNjS_HfIfBZO0K9Dg&v=1&r=http%3a%2f%2fwww.cnet.com%2fnews%2fmicrosoft-made-the-perfect-surface-pro-4-cover-for-nfl-fans%2f&p=DevEx,5027.1",
        "image": {
          "thumbnail": {
            "contentUrl": "https://www.bing.com/th?id=ON.0CA861D442848253DC54F9CD9952237D&pid=News",
            "width": 300,
            "height": 250
          }
        },
        "description": "Preseason games, last year's star quarterback on the latest cover of GQ and another collaboration between the NFL and Microsoft -- make no doubt about it, football season is here. Just in time for all of the fun, Microsoft has released an officially ...",
        "about": [
          {
            "readLink": "https://api.cognitive.microsoft.com/api/v5/entities/a093e9b9-90f5-a3d5-c4b8-5855e1b01f85",
            "name": "Microsoft"
          },
          {
            "readLink": "https://api.cognitive.microsoft.com/api/v5/entities/8b273c77-f371-ce77-0208-f4aba9a9764f",
            "name": "NFL"
          },
          {
            "readLink": "https://api.cognitive.microsoft.com/api/v5/entities/5715dc67-2d49-b1da-0ce1-0bb809fa81a9",
            "name": "Surface Pro"
          }
        ],
        "provider": [
          {
            "_type": "Organization",
            "name": "CNet"
          }
        ],
        "datePublished": "2016-08-15T21:21:00",
        "category": "Sports"
      },
      {
        "name": "Microsoft Warns Windows 10 Has A Serious Problem",
        "url": "http://www.bing.com/cr?IG=3D19289E347C46BA95F698E3F30282C9&CID=240A0E9368C4603C080907E169F56148&rd=1&h=Pb0L11hXkJfuDQO8UseOyrQ1uo_KG3ZHaESZv1JFCMA&v=1&r=http%3a%2f%2fwww.forbes.com%2fsites%2fgordonkelly%2f2016%2f08%2f15%2fmicrosoft-warns-windows-10-anniversary-update-crashes-problems%2f&p=DevEx,5029.1",
        "image": {
          "thumbnail": {
            "contentUrl": "https://www.bing.com/th?id=ON.7646574B0B50E05B5185FFC493BF3D38&pid=News",
            "width": 700,
            "height": 393
          }
        },
        "description": "The ‘Anniversary Update’ is the largest and most important Windows 10 upgrade so far. It is also compulsory, but as it began rolling out reports followed that the mega update is causing PCs to freeze. Now Microsoft has confirmed one major issue and ...",
        "about": [
          {
            "readLink": "https://api.cognitive.microsoft.com/api/v5/entities/a093e9b9-90f5-a3d5-c4b8-5855e1b01f85",
            "name": "Microsoft"
          },
          {
            "readLink": "https://api.cognitive.microsoft.com/api/v5/entities/c225e474-1294-34f1-c00a-48e4d8a83253",
            "name": "Forbes"
          },
          {
            "readLink": "https://api.cognitive.microsoft.com/api/v5/entities/16aeb6d9-9098-0a40-4970-8e46a4fcee12",
            "name": "Microsoft Windows"
          }
        ],
        "provider": [
          {
            "_type": "Organization",
            "name": "Forbes"
          }
        ],
        "datePublished": "2016-08-15T19:20:00",
        "category": "ScienceAndTechnology"
      },
      {
        "name": "Microsoft Office iPhone update lets you write, doodle, scribble with your finger",
        "url": "http://www.bing.com/cr?IG=3D19289E347C46BA95F698E3F30282C9&CID=240A0E9368C4603C080907E169F56148&rd=1&h=by7yVA8om6bf45MDGMNYL7C12IQ066Qfo3f5KEzyzwk&v=1&r=http%3a%2f%2fwww.digitaltrends.com%2fmobile%2fmicrosoft-office-iphone-update-finger-doodle%2f&p=DevEx,5031.1",
        "image": {
          "thumbnail": {
            "contentUrl": "https://www.bing.com/th?id=ON.2CF0254981B80F7009652B159A08DA8E&pid=News",
            "width": 640,
            "height": 427
          }
        },
        "description": "We may have done away with the stylus when we got rid of those Palm Pilots, but now your finger can serve as a substitute when you use Microsoft Office for iPhone. That’s right — you can now doodle, scribble, or be one of the few people capable of ...",
        "about": [
          {
            "readLink": "https://api.cognitive.microsoft.com/api/v5/entities/b6c6d65c-4f80-60fb-2799-08ad9229faf7",
            "name": "Microsoft Office"
          },
          {
            "readLink": "https://api.cognitive.microsoft.com/api/v5/entities/ceeab753-899f-4459-8ceb-d64ec0992439",
            "name": "iPhone"
          }
        ],
        "provider": [
          {
            "_type": "Organization",
            "name": "Digital Trends"
          }
        ],
        "datePublished": "2016-08-15T19:32:00",
        "video": {
          "name": "Microsoft Office iPhone update lets you write, doodle, scribble with your finger",
          "thumbnailUrl": "https://www.bing.com/th?id=ON.2AC8A53AADA4D16C52E17193DCC9106E&pid=News",
          "embedHtml": "<iframe src=\"http://content.jwplatform.com/players/jkhrd7SF-ERPbx32c.html\" width=\"480\" height=\"270\" frameBorder=\"0\"scrolling=\"auto\"></iframe>",
          "allowHttpsEmbed": true,
          "thumbnail": {
            "width": 480,
            "height": 302
          }
        },
        "category": "ScienceAndTechnology"
      },
      {
        "name": "Microsoft introduces NFL Type Covers for your Surface",
        "url": "http://www.bing.com/cr?IG=3D19289E347C46BA95F698E3F30282C9&CID=240A0E9368C4603C080907E169F56148&rd=1&h=q-v2-F-eR-8Msu2cAvnGMnSeKkOuik41P59Y4AqJwhw&v=1&r=http%3a%2f%2fwww.theverge.com%2f2016%2f8%2f15%2f12480644%2fmicrosoft-surface-type-cover-nfl-designs&p=DevEx,5033.1",
        "image": {
          "thumbnail": {
            "contentUrl": "https://www.bing.com/th?id=ON.0524055D3B6A50EA94E959E7BBD8ACF7&pid=News",
            "width": 700,
            "height": 467
          }
        },
        "description": "The NFL is well into its first week of preseason, and Microsoft is celebrating the return of football to our TV screens with some new Surface Type Covers. There are 32 designs to pick from, featuring all the team logos, and the Type Covers will work with a ...",
        "about": [
          {
            "readLink": "https://api.cognitive.microsoft.com/api/v5/entities/a093e9b9-90f5-a3d5-c4b8-5855e1b01f85",
            "name": "Microsoft"
          },
          {
            "readLink": "https://api.cognitive.microsoft.com/api/v5/entities/2770a656-7683-c355-ec8b-9076037d5a10",
            "name": "NFL"
          },
          {
            "readLink": "https://api.cognitive.microsoft.com/api/v5/entities/d3cf09a9-76dd-973e-2179-47f7f24c5e37",
            "name": "Microsoft Surface"
          }
        ],
        "mentions": [
          {
            "name": "Microsoft"
          },
          {
            "name": "NFL"
          },
          {
            "name": "Microsoft Surface"
          }
        ],
        "provider": [
          {
            "_type": "Organization",
            "name": "The Verge"
          }
        ],
        "datePublished": "2016-08-15T20:09:00",
        "video": {
          "name": "Microsoft introduces NFL Type Covers for your Surface",
          "thumbnailUrl": "https://www.bing.com/th?id=ON.4D189410AAC03DE30CE58904FF8E2EF6&pid=News",
          "allowHttpsEmbed": true,
          "thumbnail": {
            "width": 480,
            "height": 270
          }
        },
        "category": "ScienceAndTechnology"
      },
      {
        "name": "Microsoft to move to monthly patch rollups for Windows 7, 8.1 as of October 2016",
        "url": "http://www.bing.com/cr?IG=3D19289E347C46BA95F698E3F30282C9&CID=240A0E9368C4603C080907E169F56148&rd=1&h=OlTeK_mlu1eX46ouUIlzFlrxUgDXaaykVrNsJ6JNxAg&v=1&r=http%3a%2f%2fwww.zdnet.com%2farticle%2fmicrosoft-to-move-to-monthly-patch-rollups-for-windows-7-8-1-as-of-october-2016%2f&p=DevEx,5035.1",
        "image": {
          "thumbnail": {
            "contentUrl": "https://www.bing.com/th?id=ON.04921588E724B1E04274455DE5753BB4&pid=News",
            "width": 270,
            "height": 192
          }
        },
        "description": "In May this year, Microsoft came through with its promised convenience rollup of updates and fixes for Windows 7. At that time, officials said to expect at some point that Microsoft would move to a monthly patching model for Windows 7, 8.1, Windows Server ...",
        "about": [
          {
            "readLink": "https://api.cognitive.microsoft.com/api/v5/entities/0a5bcfe5-6aed-ed55-326f-812e10ec5479",
            "name": "Windows 7"
          },
          {
            "readLink": "https://api.cognitive.microsoft.com/api/v5/entities/a093e9b9-90f5-a3d5-c4b8-5855e1b01f85",
            "name": "Microsoft"
          }
        ],
        "provider": [
          {
            "_type": "Organization",
            "name": "ZDNet"
          }
        ],
        "datePublished": "2016-08-15T21:12:00",
        "category": "ScienceAndTechnology"
      },
      {
        "name": "Microsoft’s HoloLens Technology Adopted by Israeli Military",
        "url": "http://www.bing.com/cr?IG=3D19289E347C46BA95F698E3F30282C9&CID=240A0E9368C4603C080907E169F56148&rd=1&h=7zjZdNMW6mH6PTTEB5dHaV3hq0QoSJY2wxgsWVvMF_c&v=1&r=http%3a%2f%2fwww.bloomberg.com%2fnews%2farticles%2f2016-08-15%2fmicrosoft-s-hololens-technology-adopted-by-israeli-military&p=DevEx,5037.1",
        "image": {
          "thumbnail": {
            "contentUrl": "https://www.bing.com/th?id=ON.DBC4F0486B63CE948A05E13710EF0E0F&pid=News",
            "width": 488,
            "height": 325
          }
        },
        "description": "If Pokemon Go achieved one thing, it was showing the world that augmented reality technologies are ready for the mainstream. Israel’s military thinks AR is ready for another use: battlefield training. The Israeli army’s C2 Systems Department recently ...",
        "about": [
          {
            "readLink": "https://api.cognitive.microsoft.com/api/v5/entities/ebf1abd7-9ec4-7875-6a41-a8aaa77bdbb2",
            "name": "Technology"
          },
          {
            "readLink": "https://api.cognitive.microsoft.com/api/v5/entities/c5ad466d-fd68-f389-4727-7f3b9daaebf6",
            "name": "Bloomberg L.P."
          }
        ],
        "provider": [
          {
            "_type": "Organization",
            "name": "Bloomberg"
          }
        ],
        "datePublished": "2016-08-15T18:17:00",
        "category": "ScienceAndTechnology"
      },
      {
        "name": "Microsoft Research and MIT unveil DuoSkin, the latest in smart tattoos",
        "url": "http://www.bing.com/cr?IG=3D19289E347C46BA95F698E3F30282C9&CID=240A0E9368C4603C080907E169F56148&rd=1&h=G-1i7THIn6sdFwFNzUkQnbNKFQm50cqJQ1JtdL52piQ&v=1&r=http%3a%2f%2fwww.geekwire.com%2f2016%2fmicrosoft-research-mit-smart-tattoo-duoskin%2f&p=DevEx,5039.1",
        "image": {
          "thumbnail": {
            "contentUrl": "https://www.bing.com/th?id=ON.6640091D0F46B32FCFFCA8E6F32A9F1C&pid=News",
            "width": 630,
            "height": 424
          }
        },
        "description": "A DuoSkin touch-slider tattoo uses gold and silver leaf. (Credit: Jimmy Day / MIT / MSR) Smart tattoos made out of super-thin electronics have been a thing for years, but the technology is getting closer to fashionable prime time. Microsoft Research has ...",
        "about": [
          {
            "readLink": "https://api.cognitive.microsoft.com/api/v5/entities/f85986a4-3126-0423-6d1d-7a1f6d71e607",
            "name": "Microsoft Research"
          }
        ],
        "provider": [
          {
            "_type": "Organization",
            "name": "Geek Wire"
          }
        ],
        "datePublished": "2016-08-15T18:07:00",
        "category": "ScienceAndTechnology"
      },
      {
        "name": "Microsoft extends security lifeline for pre-Windows 10 users and here's why",
        "url": "http://www.bing.com/cr?IG=3D19289E347C46BA95F698E3F30282C9&CID=240A0E9368C4603C080907E169F56148&rd=1&h=7wM4SpN744aSCSqrniYlZeGbF_GRvg4gd3ZSerI9AVM&v=1&r=http%3a%2f%2fwww.techradar.com%2fnews%2fsoftware%2foperating-systems%2fmicrosoft-extends-security-lifeline-for-pre-windows-10-users-and-here-s-why-1326565&p=DevEx,5041.1",
        "image": {
          "thumbnail": {
            "contentUrl": "https://www.bing.com/th?id=ON.3AF765CC185C24352C3B0E5BA2C7283E&pid=News",
            "width": 320,
            "height": 180
          }
        },
        "description": "Microsoft has decided, once again, that it will give more breathing room to users and businesses with Skylake processors who haven't yet upgraded to Windows 10. It was back in January that Redmond first announced that systems running Skylake CPUs (and ...",
        "about": [
          {
            "readLink": "https://api.cognitive.microsoft.com/api/v5/entities/a093e9b9-90f5-a3d5-c4b8-5855e1b01f85",
            "name": "Microsoft"
          },
          {
            "readLink": "https://api.cognitive.microsoft.com/api/v5/entities/16aeb6d9-9098-0a40-4970-8e46a4fcee12",
            "name": "Microsoft Windows"
          }
        ],
        "provider": [
          {
            "_type": "Organization",
            "name": "TechRadar"
          }
        ],
        "datePublished": "2016-08-15T19:50:00",
        "category": "ScienceAndTechnology"
      },
      {
        "name": "MSFT Stock: Can Microsoft Corporation Clear Its Murky Outlook?",
        "url": "http://www.bing.com/cr?IG=3D19289E347C46BA95F698E3F30282C9&CID=240A0E9368C4603C080907E169F56148&rd=1&h=UoHsn9THsdUsBqJoTnTgT7TOArZYiN0c5fMFQYh5kX8&v=1&r=http%3a%2f%2finvestorplace.com%2f2016%2f08%2fmicrosoft-msft-stock-murky-outlook%2f&p=DevEx,5043.1",
        "image": {
          "thumbnail": {
            "contentUrl": "https://www.bing.com/th?id=ON.006A043409291E0ABB7CA010A8B2F9F8&pid=News",
            "width": 300,
            "height": 165
          }
        },
        "description": "It appeared that MSFT was being left in the dust, forever tied to stagnating personal computers and a disastrous acquisition of Nokia Corp (ADR) (NYSE:NOK) to try and break into the smart phone space. But rather quietly, Microsoft developed the Surface ...",
        "about": [
          {
            "readLink": "https://api.cognitive.microsoft.com/api/v5/entities/a093e9b9-90f5-a3d5-c4b8-5855e1b01f85",
            "name": "Microsoft"
          }
        ],
        "provider": [
          {
            "_type": "Organization",
            "name": "Investor Place"
          }
        ],
        "datePublished": "2016-08-15T20:57:00",
        "category": "ScienceAndTechnology"
      },
      {
        "name": "Microsoft rolls out a new Authenticator app for Android and iOS, makes 2FA simpler",
        "url": "http://www.bing.com/cr?IG=3D19289E347C46BA95F698E3F30282C9&CID=240A0E9368C4603C080907E169F56148&rd=1&h=977mX2Qkm6ZybOwCiLZsfIEnA-VLqbamcpiQipifGoA&v=1&r=http%3a%2f%2fwww.pcworld.com%2farticle%2f3107644%2fsecurity%2fmicrosoft-rolls-out-a-new-authenticator-app-for-android-and-ios-makes-2fa-simpler.html&p=DevEx,5045.1",
        "image": {
          "thumbnail": {
            "contentUrl": "https://www.bing.com/th?id=ON.25120BD48DB927F5175011F9654D061A&pid=News",
            "width": 580,
            "height": 427
          }
        },
        "description": "Leave it to Microsoft to make something as simple as a two-factor authentication (2FA) app as complicated as possible. Thankfully, Microsoft is cleaning up its hodge-podge of authenticator apps that include Azure Authenticator and Microsoft Account on ...",
        "about": [
          {
            "readLink": "https://api.cognitive.microsoft.com/api/v5/entities/16e46246-2257-643b-488c-f1572d8a9817",
            "name": "iOS"
          },
          {
            "readLink": "https://api.cognitive.microsoft.com/api/v5/entities/a093e9b9-90f5-a3d5-c4b8-5855e1b01f85",
            "name": "Microsoft"
          }
        ],
        "provider": [
          {
            "_type": "Organization",
            "name": "PC World"
          }
        ],
        "datePublished": "2016-08-15T21:11:00",
        "category": "ScienceAndTechnology"
      },
      {
        "name": "Microsoft Shuttering Azure RemoteApp, Turns to Citrix",
        "url": "http://www.bing.com/cr?IG=3D19289E347C46BA95F698E3F30282C9&CID=240A0E9368C4603C080907E169F56148&rd=1&h=4bofexlCO_5lLcSKEpbTDc7dRFsCLK8CqV9QHitnd78&v=1&r=http%3a%2f%2fwww.eweek.com%2fcloud%2fmicrosoft-shuttering-azure-remoteapp-turns-to-citrix.html&p=DevEx,5047.1",
        "image": {
          "thumbnail": {
            "contentUrl": "https://www.bing.com/th?id=ON.67976B78D16E0A5C5AF91B205954C856&pid=News",
            "width": 290,
            "height": 195
          }
        },
        "description": "The companies partner to deliver the XenApp Express application virtualization service, eventually replacing Microsoft's Azure RemoteApp. Azure RemoteApp, Microsoft's cloud-based remote application delivery service, is shutting down in 2017. Taking its ...",
        "about": [
          {
            "readLink": "https://api.cognitive.microsoft.com/api/v5/entities/a093e9b9-90f5-a3d5-c4b8-5855e1b01f85",
            "name": "Microsoft"
          },
          {
            "readLink": "https://api.cognitive.microsoft.com/api/v5/entities/cf3abf7d-e379-2693-f765-6da6b9fa9149",
            "name": "Windows Azure"
          },
          {
            "readLink": "https://api.cognitive.microsoft.com/api/v5/entities/c5b58827-41f6-58fe-de60-60cc3ac4073f",
            "name": "Citrix"
          }
        ],
        "provider": [
          {
            "_type": "Organization",
            "name": "eWeek"
          }
        ],
        "datePublished": "2016-08-15T21:08:00",
        "category": "ScienceAndTechnology"
      },
      {
        "name": "Microsoft announces changes to servicing models for Windows 7 and Windows 8.1",
        "url": "http://www.bing.com/cr?IG=3D19289E347C46BA95F698E3F30282C9&CID=240A0E9368C4603C080907E169F56148&rd=1&h=0JtYMxP2NyHBEX6_ClV8H4v7LCf4K87tRkGcOnObEk0&v=1&r=http%3a%2f%2fmspoweruser.com%2fmicrosoft-announces-changes-to-servicing-models-for-windows-7-and-windows-8-1%2f&p=DevEx,5049.1",
        "image": {
          "thumbnail": {
            "contentUrl": "https://www.bing.com/th?id=ON.3335B68D6F67307316E8589F78991DD1&pid=News",
            "width": 700,
            "height": 393
          }
        },
        "description": "Microsoft today announced changes for servicing models for Windows 7 SP1 and Windows 8.1. Till now, Microsoft has released individual patches for these platforms, which allowed organizations to be selective with the updates they deployed. This resulted in ...",
        "about": [
          {
            "readLink": "https://api.cognitive.microsoft.com/api/v5/entities/0a5bcfe5-6aed-ed55-326f-812e10ec5479",
            "name": "Windows 7"
          },
          {
            "readLink": "https://api.cognitive.microsoft.com/api/v5/entities/a093e9b9-90f5-a3d5-c4b8-5855e1b01f85",
            "name": "Microsoft"
          }
        ],
        "provider": [
          {
            "_type": "Organization",
            "name": "MSPoweruser"
          }
        ],
        "datePublished": "2016-08-15T20:54:00",
        "category": "ScienceAndTechnology"
      },
      {
        "name": "Microsoft Permanently Cuts Lumia 950, Lumia 950 XL Prices",
        "url": "http://www.bing.com/cr?IG=3D19289E347C46BA95F698E3F30282C9&CID=240A0E9368C4603C080907E169F56148&rd=1&h=Ifm1SVrCGMp0Aqe1whpRG7HBHWconqr7jaXKFOOe7ts&v=1&r=http%3a%2f%2fwww.windows10update.com%2f2016%2f08%2fmicrosoft-permanently-cuts-lumia-950-lumia-950-xl-prices%2f&p=DevEx,5051.1",
        "image": {
          "thumbnail": {
            "contentUrl": "https://www.bing.com/th?id=ON.DA19C13CBB04BAF8757859C3CFDCEE2C&pid=News",
            "width": 696,
            "height": 522
          }
        },
        "description": "Wonder how will this impact the upcoming Continuum-enabled devices! Microsoft has just made the price cuts of the Lumia 950 and 950 XL smartphones official. Permanently. The two devices are reduced by $150 and $200 respectively. Both phones were discounted ...",
        "about": [
          {
            "readLink": "https://api.cognitive.microsoft.com/api/v5/entities/16aeb6d9-9098-0a40-4970-8e46a4fcee12",
            "name": "Microsoft Windows"
          },
          {
            "readLink": "https://api.cognitive.microsoft.com/api/v5/entities/a093e9b9-90f5-a3d5-c4b8-5855e1b01f85",
            "name": "Microsoft"
          },
          {
            "readLink": "https://api.cognitive.microsoft.com/api/v5/entities/5ffc654b-d60d-4e3e-e8aa-64710142f36d",
            "name": "Price"
          }
        ],
        "provider": [
          {
            "_type": "Organization",
            "name": "windows10update.com"
          }
        ],
        "datePublished": "2016-08-15T21:02:00",
        "category": "ScienceAndTechnology"
      },
      {
        "name": "Microsoft is First to Incorporate Fabric Into Laptop Design",
        "url": "http://www.bing.com/cr?IG=3D19289E347C46BA95F698E3F30282C9&CID=240A0E9368C4603C080907E169F56148&rd=1&h=NP13y8jRPs0SszKOu-_dpfQLK-qJzrfiE19dhUZoD2Y&v=1&r=http%3a%2f%2fwwd.com%2ffashion-news%2ffashion-scoops%2fmicrosoft-surface-laptop-alcantara-textile-fabric-10506769%2f&p=DevEx,5053.1",
        "image": {
          "thumbnail": {
            "contentUrl": "https://www.bing.com/th?id=ON.CA48A320AABA20623AF06E830FF94346&pid=News",
            "width": 640,
            "height": 427
          }
        },
        "description": "Merging fabric to metal seems an unpredictable combination, but Microsoft Corp. designer Rachel Bell was ready to elevate the Surface laptop fabric beyond the computer cover. Bell, who started life as a tailor and fashion designer, recalled coming across ...",
        "provider": [
          {
            "_type": "Organization",
            "name": "Women's Wear Daily"
          }
        ],
        "datePublished": "2016-08-15T18:25:00"
      },
      {
        "name": "Microsoft Is Taking No Chances with Azure Stack Rollout",
        "url": "https://www.bing.com/cr?IG=3D19289E347C46BA95F698E3F30282C9&CID=240A0E9368C4603C080907E169F56148&rd=1&h=HLv6bQ-amcZcCH5V77PP9SDOghGpZ5J5pcpSu_b0o0E&v=1&r=https%3a%2f%2fredmondmag.com%2fBlogs%2fThe-Schwartz-Report%2f2016%2f08%2fNo-Chances-with-Azure-Stack-Rollout.aspx&p=DevEx,5055.1",
        "image": {
          "thumbnail": {
            "contentUrl": "https://www.bing.com/th?id=ON.5B5043B6A306BC4EA017D03B163E5500&pid=News",
            "width": 647,
            "height": 450
          }
        },
        "description": "Some early testers of the Azure Stack Technical Preview were angered last month by Microsoft's decision to say the software will only be offered on integrated systems provided by Dell, Hewlett Packard Enterprise and Lenovo. Some say that the move will put ...",
        "about": [
          {
            "readLink": "https://api.cognitive.microsoft.com/api/v5/entities/a093e9b9-90f5-a3d5-c4b8-5855e1b01f85",
            "name": "Microsoft"
          },
          {
            "readLink": "https://api.cognitive.microsoft.com/api/v5/entities/cf3abf7d-e379-2693-f765-6da6b9fa9149",
            "name": "Windows Azure"
          },
          {
            "readLink": "https://api.cognitive.microsoft.com/api/v5/entities/3cc15cce-c805-b006-3bc4-5633d08a5825",
            "name": "Stack"
          }
        ],
        "provider": [
          {
            "_type": "Organization",
            "name": "Redmond magazine"
          }
        ],
        "datePublished": "2016-08-15T20:42:00",
        "category": "ScienceAndTechnology"
      },
      {
        "name": "Microsoft Band Bug: The Weather Tile Fails to Update",
        "url": "http://www.bing.com/cr?IG=3D19289E347C46BA95F698E3F30282C9&CID=240A0E9368C4603C080907E169F56148&rd=1&h=PRBkIs6_kiY0TAwlX1SAopzUhfTqg5xs_3KKieEtSik&v=1&r=http%3a%2f%2fwinsupersite.com%2fmicrosoft-band%2fmicrosoft-band-bug-weather-tile-fails-update&p=DevEx,5057.1",
        "image": {
          "thumbnail": {
            "contentUrl": "https://www.bing.com/th?id=ON.83A1270A1AA303061CBE4B87F5240864&pid=News",
            "width": 595,
            "height": 335
          }
        },
        "description": "Many have found that the weather tile for the Microsoft Band no longer updates automatically. Originally, the weather tile was supposed to deliver updates every 15 minutes or so. It does this by connecting to the Microsoft Health app in the background.",
        "about": [
          {
            "readLink": "https://api.cognitive.microsoft.com/api/v5/entities/d36baccd-d77d-0f20-0a4f-186cf36b998f",
            "name": "Bug"
          },
          {
            "readLink": "https://api.cognitive.microsoft.com/api/v5/entities/a093e9b9-90f5-a3d5-c4b8-5855e1b01f85",
            "name": "Microsoft"
          },
          {
            "readLink": "https://api.cognitive.microsoft.com/api/v5/entities/a2589553-71c8-4920-a033-6103e8e77382",
            "name": "Tile"
          }
        ],
        "provider": [
          {
            "_type": "Organization",
            "name": "SuperSite For Windows"
          }
        ],
        "datePublished": "2016-08-15T21:02:00",
        "category": "ScienceAndTechnology"
      },
      {
        "name": "Microsoft Creates a Smart Tattoo That Lets You Control a Phone and Garage Doors",
        "url": "http://www.bing.com/cr?IG=3D19289E347C46BA95F698E3F30282C9&CID=240A0E9368C4603C080907E169F56148&rd=1&h=MdQpKon5V4fUiv20LtZU4_zdRecaaEb1qmd3qTmcT1Y&v=1&r=http%3a%2f%2fnews.softpedia.com%2fnews%2fmicrosoft-creates-a-smart-tattoo-that-lets-you-control-a-phone-and-garage-doors-507301.shtml&p=DevEx,5059.1",
        "image": {
          "thumbnail": {
            "contentUrl": "https://www.bing.com/th?id=ON.FC234A23281FDCA408CA0FB51616DACB&pid=News",
            "width": 700,
            "height": 466
          }
        },
        "description": "The wearables business is growing at a really fast pace, and more companies seem to be interested in this side of the industry, but while the majority are focusing on the traditional products, such as smartwatches, Microsoft wants to go way beyond this ...",
        "about": [
          {
            "readLink": "https://api.cognitive.microsoft.com/api/v5/entities/b8b9625e-56e0-dfcb-e4f9-9f5a4aa0a9d0",
            "name": "The Doors"
          },
          {
            "readLink": "https://api.cognitive.microsoft.com/api/v5/entities/a093e9b9-90f5-a3d5-c4b8-5855e1b01f85",
            "name": "Microsoft"
          },
          {
            "readLink": "https://api.cognitive.microsoft.com/api/v5/entities/be35cb67-d94e-5f72-4fa7-5aa40f46a43c",
            "name": "Tattoo"
          }
        ],
        "provider": [
          {
            "_type": "Organization",
            "name": "Softpedia News"
          }
        ],
        "datePublished": "2016-08-15T08:53:00",
        "category": "ScienceAndTechnology"
      },
      {
        "name": "Microsoft Accidentally Leaks Key to Windows Backdoor",
        "url": "https://www.bing.com/cr?IG=3D19289E347C46BA95F698E3F30282C9&CID=240A0E9368C4603C080907E169F56148&rd=1&h=2SNQhzJJNm7m3SthFJ9JvNOwHRdqlhFbp9DwfZDXa6U&v=1&r=https%3a%2f%2fwww.schneier.com%2fblog%2farchives%2f2016%2f08%2fmicrosoft_accid.html&p=DevEx,5061.1",
        "description": "In a cautionary tale to those who favor government-mandated backdoors to security systems, Microsoft accidentally leaked the key protecting its UEFI Secure boot feature. As we all know, the problems with backdoors are less the cryptography and more the ...",
        "about": [
          {
            "readLink": "https://api.cognitive.microsoft.com/api/v5/entities/72333fe4-28ef-0d75-d7dd-29b1eb1f2931",
            "name": "Bruce Schneier"
          },
          {
            "readLink": "https://api.cognitive.microsoft.com/api/v5/entities/a093e9b9-90f5-a3d5-c4b8-5855e1b01f85",
            "name": "Microsoft"
          },
          {
            "readLink": "https://api.cognitive.microsoft.com/api/v5/entities/16aeb6d9-9098-0a40-4970-8e46a4fcee12",
            "name": "Microsoft Windows"
          }
        ],
        "provider": [
          {
            "_type": "Organization",
            "name": "www.schneier.com"
          }
        ],
        "datePublished": "2016-08-15T21:10:00"
      },
      {
        "name": "UTSA, NRG Energy and Microsoft announce new flow battery research initiative",
        "url": "http://www.bing.com/cr?IG=3D19289E347C46BA95F698E3F30282C9&CID=240A0E9368C4603C080907E169F56148&rd=1&h=sOpulkANp-n-xRqLFGJ8EX0ULH15ASHbmH2Ue7-P2B0&v=1&r=http%3a%2f%2fwww.utsa.edu%2ftoday%2f2016%2f08%2fbatteryresearch.html&p=DevEx,5063.1",
        "image": {
          "thumbnail": {
            "contentUrl": "https://www.bing.com/th?id=ON.112165EA49F0B464EE0B5D071E43BE9B&pid=News",
            "width": 334,
            "height": 280
          }
        },
        "description": "sejhrfkerbfeurgfkberufkberfkuewgrfkuyewrgfkuyegrkufywegrkuyfgwekurygfkuerygf",
        "about": [
          {
            "readLink": "https://api.cognitive.microsoft.com/api/v5/entities/a093e9b9-90f5-a3d5-c4b8-5855e1b01f85",
            "name": "Microsoft"
          },
          {
            "readLink": "https://api.cognitive.microsoft.com/api/v5/entities/d671251c-7544-d9c4-65b8-9240baad00d7",
            "name": "University of Texas at San Antonio"
          }
        ],
        "provider": [
          {
            "_type": "Organization",
            "name": "The University Of Texas At San Antonio"
          }
        ],
        "datePublished": "2016-08-15T20:29:00",
        "category": "ScienceAndTechnology"
      }
    ]
  }


class mockNewsApi {
  static getArticles(searchTerm) {
    return new Promise(resolve => {
      setTimeout(() => {
        resolve(Object.assign({}, articlesFromBing));
      }, delay);
    });
  }
}

export default mockNewsApi;
