import delay from './delay';

const articles = 

  {
    "status": "OK",
    "usage": "By accessing AlchemyAPI or using information generated by AlchemyAPI, you are agreeing to be bound by the AlchemyAPI Terms of Use: http://www.alchemyapi.com/company/terms.html",
    "totalTransactions": "45",
    "result": {
      "docs": [
        {
          "id": "NjM1NzQ1Nzc4OHwxNDcxMDU3MzQ3",
          "source": {
            "enriched": {
              "url": {
                "text": "Trump says he will be the \u2018law and order\u2019 president. Do we ever need some law and order. ...",
                "title": "Third Party & Independents: Mister Dillon, Mister Dillon !!!"
              }
            },
            "original": {
              "url": "http://www.watchblog.com/thirdparty/archives/009465.html"
            }
          },
          "timestamp": 1471057347
        },
        {
          "id": "NjMxNTc3NTI0N3wxNDcxMDUxNjk3",
          "source": {
            "enriched": {
              "url": {
                "text": " \t\t\t\t\t \t\t\t\t\t\t An opium theft leaves Swearengen trying to find common language with his supplier, as well as navigating tricky waters to deal with the mess. Meanwhile, Silas Adams, bagman for the magistrate from Yankton, arrives with bad\u00A0news for Swearengen; Bullock regrets having raised his hand at the government meeting; Merrick proposes Deadwood's first \"club\"; and an unwelcome Rev. ...",
                "title": "Deadwood: Mister Wu"
              }
            },
            "original": {
              "url": "http://www.tv.com/shows/deadwood/mister-wu-322720/"
            }
          },
          "timestamp": 1471051697
        },
        {
          "id": "NjEzMzc1NzYxMXwxNDcxMDM0MDQ0",
          "source": {
            "enriched": {
              "url": {
                "text": "Maryland star Ben's Cat breezed a half-mile Aug. 12 at Laurel Park in his final timed work before seeking to win the $75,000 Mister Diz Stakes for the seventh successive year Aug. 20.\u00A0\nBred, owned, and trained by Hall of Fame horseman King Leatherbury, the 10-year-old Maryland-bred gelding by Parker's Storm Cat went four furlongs in :49 1/5 over Laurel's main track, registering the fourth-fastest of 12 workouts at the distance. It was the second work for Ben's Cat since his third-place finish in the Parx Dash (gr. ...",
                "title": "Ben's Cat Gears Up for 7th Mister Diz"
              }
            },
            "original": {
              "url": "http://www.bloodhorse.com/horse-racing/articles/214164/bens-cat-gears-up-for-7th-mister-diz"
            }
          },
          "timestamp": 1471034044
        },
        {
          "id": "NjA1NDY5NDgwNXwxNDcxMDI4MTky",
          "source": {
            "enriched": {
              "url": {
                "text": "TUCSON, Ariz., Aug. 12, 2016 /PRNewswire/ -- Mister Car Wash has expanded its Texas footprint with the acquisition of The Car Wash Barn based in Killeen, Texas, according to Casey Lindsay, Director of Acquisitions. \"The Car Wash Barn team developed a great operation and their dedication to the communities they serve is unmatched. ...",
                "title": "Mister Car Wash Adds Six Texas Locations"
              }
            },
            "original": {
              "url": "http://www.prnewswire.com/news-releases/mister-car-wash-adds-six-texas-locations-300313018.html"
            }
          },
          "timestamp": 1471028192
        },
        {
          "id": "NTgyNjAxOTUwOHwxNDcxMDExMDM4",
          "source": {
            "enriched": {
              "url": {
                "text": "In 1987, my primary five class were ushered into the assembly hall at Nazareth House PS by our teacher Patsy Casey to see the important man dressed in black who had come to visit our school. I have no memory of what he talked to us about, I was only nine. ...",
                "title": "Skirting the issue - Mister Bishop do you know my granda?"
              }
            },
            "original": {
              "url": "http://www.derryjournal.com/news/columnists/skirting-the-issue-mister-bishop-do-you-know-my-granda-1-7524448"
            }
          },
          "timestamp": 1471011038
        },
        {
          "id": "NTk2ODQzODI0N3wxNDcxMDAzMDIw",
          "source": {
            "enriched": {
              "url": {
                "text": "Can you hear it? Can you feel it? ...",
                "title": "Hey, mister! Mardi Gras 2017 is 200 days away"
              }
            },
            "original": {
              "url": "http://www.nola.com/mardigras/index.ssf/2016/08/mardi_gras_2017_new_orleans.html"
            }
          },
          "timestamp": 1471003020
        },
        {
          "id": "NTg4MTEwNDYzN3wxNDcwOTk5NjAw",
          "source": {
            "enriched": {
              "url": {
                "text": "\"When we first get the trucks\u00A0they look like blank UPS delivery trucks,\" said Jim Conway, co-owner and vice president of Mister Softee. \"We cut the windows into them, paint them, and deck them out with the equipment to turn them into what you see on the streets.\" ...",
                "title": "The legend of Jersey's own Mister Softee is anything but vanilla"
              }
            },
            "original": {
              "url": "http://www.nj.com/entertainment/index.ssf/2016/08/16_things_you_may_not_know_about_mister_softee.html"
            }
          },
          "timestamp": 1470999600
        }
      ],
      "status": "OK"
    }
  }


class mockNewsApi {
  static getArticles(searchTerm) {
    return new Promise(resolve => {
      setTimeout(() => {
        resolve(Object.assign({}, articles));
      }, delay);
    });
  }
}

export default mockNewsApi;
